apiVersion: v1
kind: Pod
metadata:
  name: myapp-webcolor
spec:
 containers:
 - name: myapp-webcolor
   image: 660700579747.dkr.ecr.us-east-1.amazonaws.com/assignment3ecr:v0.2nodeapp
   ports:
   - containerPort: 80
     protocol: TCP
   env:
   - name: APP_COLOR
     value: "red"
 volumes:
 - name: html
   emptyDir: {}