apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - image: 660700579747.dkr.ecr.us-east-1.amazonaws.com/assignment3ecr:v0.2nodeapp
        name: myapp
        env:
        - name: DBHOST
          value: 10.100.165.65
        - name: DBPWD
          value: "pw"
        - name: DBPORT
          value: "3306"
        ports:
        - containerPort: 80
          name: myapp
        volumeMounts:
        - name: myapp-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: myapp-persistent-storage
        persistentVolumeClaim:
          claimName: myapp-pv-claim
