apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: myapp
    tier: frontend
  type: LoadBalancer
