apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapps
spec:
  serviceName: myapps
  replicas: 2
  selector:
    matchLabels:
      app: myapps
  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
      - name: myapps
        image: 660700579747.dkr.ecr.us-east-1.amazonaws.com/assignment3ecr:v0.2nodeapp
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 1Mi
      accessModes:
      - ReadWriteOnce